# Generated by Django 4.0.1 on 2022-01-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avgrating',
            fields=[
                ('avg_rate_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('avg_rating', models.FloatField()),
                ('status', models.PositiveIntegerField(default=1)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rate_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('status', models.PositiveIntegerField(default=1)),
                ('avg_rate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.avgrating')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
            ],
        ),
    ]
