# Generated by Django 4.0.1 on 2022-01-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_avgrating_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avgrating',
            options={'default_related_name': 'avg'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'default_related_name': 'rating'},
        ),
        migrations.AlterField(
            model_name='avgrating',
            name='avg_rate_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
