# Generated by Django 4.0.1 on 2022-01-09 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_avgrating_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avgrating',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.AlterField(
            model_name='avgrating',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avgrating',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avg', to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='avg_rate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='cars.avgrating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avg_rating', to='cars.cars'),
        ),
    ]
