# Generated by Django 4.0.1 on 2022-01-09 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avgrating',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
